fix: add missing IDType parameter to BaseService subclasses
Added int as 4th generic parameter to services:
- BatchJobService
- BusinessRuleService
- RoleService
- UserService
- ForecastService
- AdjustmentService
- CustomerItemsService

Fixes TypeError: Too few arguments for BaseService